robot:
  name: g1
  asset_path: urdf/g1/g1_12dof_full.urdf
  scale: 1.0
  body_name: pelvis
  foot_names:
  - left_ankle_roll_link
  links_to_keep:
  - left_ankle_roll_link
  link_names:
  - pelvis
  - left_hip_pitch_link
  - right_hip_pitch_link
  - left_hip_roll_link
  - right_hip_roll_link
  - left_hip_yaw_link
  - right_hip_yaw_link
  - left_knee_link
  - right_knee_link
  - left_ankle_pitch_link
  - right_ankle_pitch_link
  - left_ankle_roll_link
  - right_ankle_roll_link
  dof_names:
  - left_hip_pitch_joint
  - right_hip_pitch_joint
  - left_hip_roll_joint
  - right_hip_roll_joint
  - left_hip_yaw_joint
  - right_hip_yaw_joint
  - left_knee_joint
  - right_knee_joint
  - left_ankle_pitch_joint
  - right_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_ankle_roll_joint
  diameter: 1.3955285549163818
  mass: 34.13385727999999
control:
  control_freq: 50
  dof_names:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  kp:
    left_hip_pitch_joint: 100
    left_hip_roll_joint: 100
    left_hip_yaw_joint: 100
    left_knee_joint: 200
    left_ankle_pitch_joint: 20
    left_ankle_roll_joint: 20
    right_hip_pitch_joint: 100
    right_hip_roll_joint: 100
    right_hip_yaw_joint: 100
    right_knee_joint: 200
    right_ankle_pitch_joint: 20
    right_ankle_roll_joint: 20
  kd:
    left_hip_pitch_joint: 5.0
    left_hip_roll_joint: 5.0
    left_hip_yaw_joint: 5.0
    left_knee_joint: 5.0
    left_ankle_pitch_joint: 0.2
    left_ankle_roll_joint: 0.1
    right_hip_pitch_joint: 5.0
    right_hip_roll_joint: 5.0
    right_hip_yaw_joint: 5.0
    right_knee_joint: 5.0
    right_ankle_pitch_joint: 0.2
    right_ankle_roll_joint: 0.1
  armature: 0.05
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
    - -0.5
    - 1.0
    lin_vel_y_range:
    - -0.5
    - 0.5
    ang_vel_range:
    - -1.0
    - 1.0
  note: Hopping on only its left leg. Left foot on the ground and right foot in the
    air.
pose:
  base_reset_pos:
  - 0.0
  - 0.0
  - 0.8
  base_reset_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  reset_joint_angles:
    left_hip_yaw_joint: 0.0
    left_hip_roll_joint: 0.0
    left_hip_pitch_joint: -0.1
    left_knee_joint: 0.3
    left_ankle_pitch_joint: -0.2
    left_ankle_roll_joint: 0.0
    right_hip_yaw_joint: 0.0
    right_hip_roll_joint: 0.0
    right_hip_pitch_joint: -0.1
    right_knee_joint: 0.3
    right_ankle_pitch_joint: -0.2
    right_ankle_roll_joint: 0.0
  base_init_pos:
  - 0.0
  - 0.0
  - 0.7439802885055542
  base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  body_init_pos:
  - 0.0
  - 0.0
  - 0.7439802885055542
  body_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  default_joint_angles:
    left_ankle_pitch_joint: -0.641802966594696
    left_ankle_roll_joint: 0.14481773972511292
    left_hip_pitch_joint: -0.8853517174720764
    left_hip_roll_joint: -0.07116315513849258
    left_hip_yaw_joint: 0.12627427279949188
    left_knee_joint: 1.5226458311080933
    right_ankle_pitch_joint: -0.8084814548492432
    right_ankle_roll_joint: -0.1753024160861969
    right_hip_pitch_joint: -1.0855315923690796
    right_hip_roll_joint: 0.05404437333345413
    right_hip_yaw_joint: -0.16687113046646118
    right_knee_joint: 1.889487385749817
  gait:
    base_height_target: 0.5699822902679443
    duration:
    - 0.5
    frequency:
    - 3.0
    offset:
    - 0.0
    stationary_position:
    - - 0.08000119775533676
      - 0.04999462887644768
