base_init_pos:
  - 0.0
  - 0.0
  - 0.7313347458839417
base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
base_link_name: pelvis
body_init_pos:
  - 0.0
  - 0.0
  - 0.7313347458839417
body_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
default_joint_angles:
  left_ankle_pitch_joint: -0.33980926871299744
  left_ankle_roll_joint: 0.21197949349880219
  left_hip_pitch_joint: -0.5390906929969788
  left_hip_roll_joint: -0.1554151177406311
  left_hip_yaw_joint: 0.14420707523822784
  left_knee_joint: 0.8781281113624573
  right_ankle_pitch_joint: -0.871567964553833
  right_ankle_roll_joint: 0.09691190719604492
  right_hip_pitch_joint: -1.266218662261963
  right_hip_roll_joint: -0.023500187322497368
  right_hip_yaw_joint: 0.09641847759485245
  right_knee_joint: 2.1914522647857666
diameter: 1.3955285549163818
dof_names:
  - left_hip_pitch_joint
  - right_hip_pitch_joint
  - left_hip_roll_joint
  - right_hip_roll_joint
  - left_hip_yaw_joint
  - right_hip_yaw_joint
  - left_knee_joint
  - right_knee_joint
  - left_ankle_pitch_joint
  - right_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_ankle_roll_joint
extremity ids:
  - 11
  - 12
feet_link_names:
  - left_ankle_roll_link
gait:
  base_height_target: 0.6799876689910889
  duration:
    - 0.5
  frequency:
    - 3.0
  offset:
    - 0.0
  stationary_position:
    - - 0.06699884682893753
      - -0.002997222589328885
link_names:
  - pelvis
  - left_hip_pitch_link
  - right_hip_pitch_link
  - left_hip_roll_link
  - right_hip_roll_link
  - left_hip_yaw_link
  - right_hip_yaw_link
  - left_knee_link
  - right_knee_link
  - left_ankle_pitch_link
  - right_ankle_pitch_link
  - left_ankle_roll_link
  - right_ankle_roll_link
mass: 34.13385727999999
robot:
  asset_path: urdf/g1/g1_12dof.urdf
  merge_fixed_links: true
  name: g1
  numeric_adjustment: true
  scale: 1.0
task: Hopping on only its left leg. Left foot on the ground and right foot in the air.
