base_init_quat:
- 0.7071067690849304
- 0.0
- 0.7071068286895752
- 4.214685134229512e-08
base_link_name: base
body_init_quat:
- 0.7071067690849304
- 0.0
- 0.7071068286895752
- 4.214685134229512e-08
robot:
  asset_path: urdf/leap_hand/leap_hand_right_glb.urdf
  merge_fixed_links: true
  numeric_adjustment: false
  scale: 2.0
task: walk with palm parallel to the ground, middle finger pointing forward, all fingertips
  placing on the ground
