base_init_pos:
  - 0.0
  - 0.0
  - 0.8707888722419739
base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
base_link_name: pelvis
body_init_pos:
  - 0.0
  - 0.0
  - 0.8707888722419739
body_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
default_joint_angles:
  left_ankle_pitch_joint: -0.5451169013977051
  left_ankle_roll_joint: 0.01958938129246235
  left_hip_pitch_joint: -0.7199617028236389
  left_hip_roll_joint: -0.026046792045235634
  left_hip_yaw_joint: 0.01717286743223667
  left_knee_joint: 1.265243649482727
  right_ankle_pitch_joint: -0.5451169013977051
  right_ankle_roll_joint: -0.01958938129246235
  right_hip_pitch_joint: -0.7199617028236389
  right_hip_roll_joint: 0.026046792045235634
  right_hip_yaw_joint: -0.01717286743223667
  right_knee_joint: 1.265243649482727
diameter: 1.3356688022613525
dof_names:
  - left_hip_yaw_joint
  - right_hip_yaw_joint
  - left_hip_pitch_joint
  - right_hip_pitch_joint
  - left_hip_roll_joint
  - right_hip_roll_joint
  - left_knee_joint
  - right_knee_joint
  - left_ankle_pitch_joint
  - right_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_ankle_roll_joint
extremity ids:
  - 11
  - 12
feet_link_names:
  - left_ankle_roll_link
  - right_ankle_roll_link
gait:
  base_height_target: 0.8257883191108704
  duration:
    - 0.5
    - 0.5
  frequency:
    - 3.0
    - 3.0
  offset:
    - 0.0
    - 0.5
  stationary_position:
    - - 0.05509040132164955
      - 0.1500123292207718
    - - 0.05509040132164955
      - -0.1500123292207718
link_names:
  - pelvis
  - left_hip_yaw_link
  - right_hip_yaw_link
  - left_hip_pitch_link
  - right_hip_pitch_link
  - left_hip_roll_link
  - right_hip_roll_link
  - left_knee_link
  - right_knee_link
  - left_ankle_pitch_link
  - right_ankle_pitch_link
  - left_ankle_roll_link
  - right_ankle_roll_link
mass: 66.98400000000002
robot:
  asset_path: urdf/h1_2/h1_2_simp.urdf
  merge_fixed_links: true
  name: h1
  numeric_adjustment: true
  scale: 1.0
task: walk with 2 legs
