environment:
  base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  num_actions: 26
  action_scale: 0.15
  observation:
    obs_scales:
      dof_pos: 1.0
      dof_vel: 1.0
      ang_vel: 1.0
  PD_stiffness:
    left_hip_roll_joint: 200.0
    left_hip_pitch_joint: 200.0
    left_hip_yaw_joint: 200.0
    left_knee_joint: 200.0
    left_ankle_roll_joint: 40.0
    left_ankle_pitch_joint: 40.0
    right_hip_roll_joint: 200.0
    right_hip_pitch_joint: 200.0
    right_hip_yaw_joint: 200.0
    right_knee_joint: 200.0
    right_ankle_roll_joint: 40.0
    right_ankle_pitch_joint: 40.0
    left_shoulder_roll_joint: 60.0
    left_shoulder_pitch_joint: 90.0
    left_shoulder_yaw_joint: 40.0
    left_elbow_joint: 80.0
    left_wrist_roll_joint: 4.0
    left_wrist_pitch_joint: 4.0
    left_wrist_yaw_joint: 4.0
    right_shoulder_roll_joint: 60.0
    right_shoulder_pitch_joint: 90.0
    right_shoulder_yaw_joint: 40.0
    right_elbow_joint: 80.0
    right_wrist_roll_joint: 4.0
    right_wrist_pitch_joint: 4.0
    right_wrist_yaw_joint: 4.0
  PD_damping:
    left_hip_roll_joint: 5.0
    left_hip_pitch_joint: 5.0
    left_hip_yaw_joint: 5.0
    left_knee_joint: 5.0
    left_ankle_roll_joint: 0.2
    left_ankle_pitch_joint: 0.4
    right_hip_roll_joint: 5.0
    right_hip_pitch_joint: 5.0
    right_hip_yaw_joint: 5.0
    right_knee_joint: 5.0
    right_ankle_roll_joint: 0.2
    right_ankle_pitch_joint: 0.4
    left_shoulder_roll_joint: 1.0
    left_shoulder_pitch_joint: 2.0
    left_shoulder_yaw_joint: 0.8
    left_elbow_joint: 2.0
    left_wrist_roll_joint: 0.2
    left_wrist_pitch_joint: 0.2
    left_wrist_yaw_joint: 0.2
    right_shoulder_roll_joint: 1.0
    right_shoulder_pitch_joint: 2.0
    right_shoulder_yaw_joint: 0.8
    right_elbow_joint: 2.0
    right_wrist_roll_joint: 0.2
    right_wrist_pitch_joint: 0.2
    right_wrist_yaw_joint: 0.2
  dof_names:
  - left_hip_roll_joint
  - left_hip_pitch_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_roll_joint
  - left_ankle_pitch_joint
  - right_hip_roll_joint
  - right_hip_pitch_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_roll_joint
  - right_ankle_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_pitch_joint
  - left_shoulder_yaw_joint
  - left_elbow_joint
  - left_wrist_roll_joint
  - left_wrist_pitch_joint
  - left_wrist_yaw_joint
  - right_shoulder_roll_joint
  - right_shoulder_pitch_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint
  - right_wrist_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint
  default_joint_angles:
    left_hip_roll_joint: 0.0
    left_hip_pitch_joint: -0.1
    left_hip_yaw_joint: 0.0
    left_knee_joint: 0.3
    left_ankle_roll_joint: 0.0
    left_ankle_pitch_joint: -0.2
    right_hip_roll_joint: 0.0
    right_hip_pitch_joint: -0.1
    right_hip_yaw_joint: 0.0
    right_knee_joint: 0.3
    right_ankle_roll_joint: 0.0
    right_ankle_pitch_joint: -0.2
    left_shoulder_roll_joint: 0.0
    left_shoulder_pitch_joint: 0.0
    left_shoulder_yaw_joint: 0.0
    left_elbow_joint: 0.0
    left_wrist_roll_joint: 0.0
    left_wrist_pitch_joint: 0.0
    left_wrist_yaw_joint: 0.0
    right_shoulder_roll_joint: 0.0
    right_shoulder_pitch_joint: 0.0
    right_shoulder_yaw_joint: 0.0
    right_elbow_joint: 0.0
    right_wrist_roll_joint: 0.0
    right_wrist_pitch_joint: 0.0
    right_wrist_yaw_joint: 0.0
