robot:
  name: anymal
  asset_path: urdf/anymal_c/urdf/anymal_c.urdf
  scale: 1.0
control:
  control_freq: 50
  kp: 190.0
  kd: 10.0
  armature: 0.0
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
    - -0.5
    - 1.0
    lin_vel_y_range:
    - -0.5
    - 0.5
    ang_vel_range:
    - -1.0
    - 1.0
pose:
  base_reset_pos:
  - 0.0
  - 0.0
  - 0.7
  base_reset_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  reset_joint_angles:
    LF_HAA: 0.
    LF_HFE: 0.
    LF_KFE: 0.
    LH_HAA: 0.
    LH_HFE: 0.
    LH_KFE: 0.
    RF_HAA: 0.
    RF_HFE: 0.
    RF_KFE: 0.
    RH_HAA: 0.
    RH_HFE: 0.
    RH_KFE: 0.