robot:
  name: anymal
  asset_path: urdf/anymal_c/urdf/anymal_c.urdf
  scale: 1.0
  body_name: base
  foot_names:
  - LF_SHANK
  - RF_SHANK
  - LH_SHANK
  - RH_SHANK
  links_to_keep:
  - LF_SHANK
  - RF_SHANK
  - LH_SHANK
  - RH_SHANK
  link_names:
  - base
  - LF_HIP
  - RF_HIP
  - LH_HIP
  - RH_HIP
  - LF_THIGH
  - RF_THIGH
  - LH_THIGH
  - RH_THIGH
  - LF_SHANK
  - RF_SHANK
  - LH_SHANK
  - RH_SHANK
  dof_names:
  - LF_HAA
  - RF_HAA
  - LH_HAA
  - RH_HAA
  - LF_HFE
  - RF_HFE
  - LH_HFE
  - RH_HFE
  - LF_KFE
  - RF_KFE
  - LH_KFE
  - RH_KFE
  diameter: 1.373038411140442
  mass: 52.13484999999999
control:
  control_freq: 50
  kp: 190.0
  kd: 10.0
  armature: 0.0
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
    - -0.5
    - 1.0
    lin_vel_y_range:
    - -0.5
    - 0.5
    ang_vel_range:
    - -1.0
    - 1.0
  note: walk naturally with four feet on the ground
pose:
  base_reset_pos:
  - 0.0
  - 0.0
  - 0.7
  base_reset_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  reset_joint_angles:
    LF_HAA: 0.0
    LF_HFE: 0.0
    LF_KFE: 0.0
    LH_HAA: 0.0
    LH_HFE: 0.0
    LH_KFE: 0.0
    RF_HAA: 0.0
    RF_HFE: 0.0
    RF_KFE: 0.0
    RH_HAA: 0.0
    RH_HFE: 0.0
    RH_KFE: 0.0
  base_init_pos:
  - 0.0
  - 0.0
  - 0.6304699778556824
  base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  body_init_pos:
  - 0.0
  - 0.0
  - 0.6304699778556824
  body_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  default_joint_angles:
    LF_HAA: 0.0
    LF_HFE: 0.0
    LF_KFE: 0.0
    LH_HAA: 0.0
    LH_HFE: 0.0
    LH_KFE: 0.0
    RF_HAA: 0.0
    RF_HFE: 0.0
    RF_KFE: 0.0
    RH_HAA: 0.0
    RH_HFE: 0.0
    RH_KFE: 0.0
  gait:
    base_height_target: 0.2849999964237213
    duration:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    frequency:
    - 3.0
    - 3.0
    - 3.0
    - 3.0
    offset:
    - 0.0
    - 0.5
    - 0.0
    - 0.5
    stationary_position:
    - - 0.35979998111724854
      - 0.28811001777648926
    - - 0.35979998111724854
      - -0.28811001777648926
    - - -0.3598000109195709
      - 0.28810998797416687
    - - -0.3598000109195709
      - -0.28810998797416687
