track_id_offset = 16384  # Set if unmatched skeleton ID

RIGID_BODY_ID_MAP = {
    # Real to Sim Rigid
    # G1
    257: "pelvis_contour_link",
    258: "torso_link",
    259: "left_rubber_hand",
    260: "right_rubber_hand",
    261: "left_ankle_roll_link",
    262: "right_ankle_roll_link",
    # Skeleton
    1 + track_id_offset: "Hips",
    2 + track_id_offset: "Spine",
    3 + track_id_offset: "Spine1",
    4 + track_id_offset: "Neck",
    5 + track_id_offset: "Head",
    6 + track_id_offset: "LeftShoulder",
    7 + track_id_offset: "LeftArm",
    8 + track_id_offset: "LeftForeArm",
    9 + track_id_offset: "LeftHand",
    10 + track_id_offset: "RightShoulder",
    11 + track_id_offset: "RightArm",
    12 + track_id_offset: "RightForeArm",
    13 + track_id_offset: "RightHand",
    14 + track_id_offset: "LeftUpLeg",
    15 + track_id_offset: "LeftLeg",
    16 + track_id_offset: "LeftFoot",
    17 + track_id_offset: "LeftToeBase",
    18 + track_id_offset: "RightUpLeg",
    19 + track_id_offset: "RightLeg",
    20 + track_id_offset: "RightFoot",
    21 + track_id_offset: "RightToeBase",
    22 + track_id_offset: "LeftHandThumb1",
    23 + track_id_offset: "LeftHandThumb2",
    24 + track_id_offset: "LeftHandThumb3",
    25 + track_id_offset: "LeftHandIndex1",
    26 + track_id_offset: "LeftHandIndex2",
    27 + track_id_offset: "LeftHandIndex3",
    28 + track_id_offset: "LeftHandMiddle1",
    29 + track_id_offset: "LeftHandMiddle2",
    30 + track_id_offset: "LeftHandMiddle3",
    31 + track_id_offset: "LeftHandRing1",
    32 + track_id_offset: "LeftHandRing2",
    33 + track_id_offset: "LeftHandRing3",
    34 + track_id_offset: "LeftHandPinky1",
    35 + track_id_offset: "LeftHandPinky2",
    36 + track_id_offset: "LeftHandPinky3",
    37 + track_id_offset: "RightHandThumb1",
    38 + track_id_offset: "RightHandThumb2",
    39 + track_id_offset: "RightHandThumb3",
    40 + track_id_offset: "RightHandIndex1",
    41 + track_id_offset: "RightHandIndex2",
    42 + track_id_offset: "RightHandIndex3",
    43 + track_id_offset: "RightHandMiddle1",
    44 + track_id_offset: "RightHandMiddle2",
    45 + track_id_offset: "RightHandMiddle3",
    46 + track_id_offset: "RightHandRing1",
    47 + track_id_offset: "RightHandRing2",
    48 + track_id_offset: "RightHandRing3",
    49 + track_id_offset: "RightHandPinky1",
    50 + track_id_offset: "RightHandPinky2",
    51 + track_id_offset: "RightHandPinky3",
}
