robot:
  name: lamp
  asset_path: urdf/lamp/lamp.urdf
  scale: 1.0
  body_name: light
  foot_names:
  - base
  links_to_keep:
  - base
  link_names:
  - base
  - rod1
  - rod2
  - light
  dof_names:
  - base_rod1_joint
  - rod1_rod2_joint
  - rod2_light_joint
  diameter: 0.3911784589290619
  mass: 2.1
control:
  control_freq: 50
  kp: 20
  kd: 0.5
  armature: 0.0
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
    - -0.5
    - 1.0
    lin_vel_y_range:
    - -0.5
    - 0.5
    ang_vel_range:
    - -0.5
    - 0.5
  note: The lamp hops with lamp itself hang over the base.
pose:
  base_init_pos:
  - 0.0
  - 0.0
  - 0.050002320110979784
  base_init_quat:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  body_init_pos:
  - 0.013914987444877625
  - -4.470348358154297e-08
  - 0.34238128662109374
  body_init_quat:
  - 0.07789929211139679
  - 0.7028027772903442
  - 0.7028027772903442
  - 0.07789932191371918
  default_joint_angles:
    base_rod1_joint: -0.08737935870885849
    rod1_rod2_joint: 0.2422485500574112
    rod2_light_joint: -0.15485365688800812
  gait:
    base_height_target: 0.2923789620399475
    duration:
    - 0.5
    frequency:
    - 3.0
    offset:
    - 0.0
    stationary_position:
    - - -1.4901161193847656e-08
      - 2.9802322387695312e-08
