base_init_quat:
- 0.5
- 0.5
- 0.5
- 0.5
base_link_name: base
body_init_quat:
- 0.5
- 0.5
- 0.5
- 0.5
default_joint_angles:
  base_rod1_joint: 0.11284080147743225
  rod1_rod2_joint: -0.1585686206817627
  rod2_light_joint: 0.04572434350848198
diameter: 0.41236698627471924
dof_names:
- base_rod1_joint
- rod1_rod2_joint
- rod2_light_joint
extremity ids:
- 3
mass: 2.1
robot:
  asset_path: urdf/lamp/lamp.urdf
  merge_fixed_links: true
  name: lamp
  numeric_adjustment: false
  scale: 1.0
task: The lamp hops with lamp itself hang over the base.
