robot:
  name: panda
  asset_path: urdf/panda_bullet/panda_nohand.urdf
  scale: 1.0
control:
  control_freq: 50
  kp: 40.0
  kd: 1.0
  armature: 0.0
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
    - 0.0
    - 1.0
    lin_vel_y_range:
    - 0.0
    - 0.0
    ang_vel_range:
    - 0.0
    - 0.0