robot:
  name: go2
  asset_path: urdf/go2/urdf/go2.urdf
  scale: 1.0
  merge_fixed_joints: false
  foot_names:
    - FL_foot
    - FR_foot
    - RL_foot
    - RR_foot
  body_name: base
control:
  control_freq: 50
  kp: 30.0
  kd: 2.0
  armature: 0.05
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
      - -0.5
      - 1.0
    lin_vel_y_range:
      - -0.5
      - 0.5
    ang_vel_range:
      - -1.0
      - 1.0
pose:
  base_reset_pos:
    - 0.0
    - 0.0
    - 0.35
  base_reset_quat:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
  reset_joint_angles:
    FL_calf_joint: -1.5
    FL_hip_joint: 0.0
    FL_thigh_joint: 0.8
    FR_calf_joint: -1.5
    FR_hip_joint: 0.0
    FR_thigh_joint: 0.8
    RL_calf_joint: -1.5
    RL_hip_joint: 0.0
    RL_thigh_joint: 1.0
    RR_calf_joint: -1.5
    RR_hip_joint: 0.0
    RR_thigh_joint: 1.0
