robot:
  name: go2
  asset_path: urdf/go2/urdf/go2.urdf
  scale: 1.0
  body_name: base
  foot_names:
  - FL_foot
  - FR_foot
  links_to_keep:
  - FL_foot
  - FR_foot
  link_names:
  - base
  - Head_upper
  - FL_hip
  - FR_hip
  - RL_hip
  - RR_hip
  - imu
  - radar
  - Head_lower
  - FL_thigh
  - FR_thigh
  - RL_thigh
  - RR_thigh
  - FL_calf
  - FR_calf
  - RL_calf
  - RR_calf
  - FL_calflower
  - FL_foot
  - FR_calflower
  - FR_foot
  - RL_calflower
  - RL_foot
  - RR_calflower
  - RR_foot
  - FL_calflower1
  - FR_calflower1
  - RL_calflower1
  - RR_calflower1
  dof_names:
  - FL_hip_joint
  - FR_hip_joint
  - RL_hip_joint
  - RR_hip_joint
  - FL_thigh_joint
  - FR_thigh_joint
  - RL_thigh_joint
  - RR_thigh_joint
  - FL_calf_joint
  - FR_calf_joint
  - RL_calf_joint
  - RR_calf_joint
  diameter: 0.8356513977050781
  mass: 15.056638385645922
control:
  control_freq: 50
  kp: 30.0
  kd: 2.0
  armature: 0.05
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
    - -0.5
    - 1.0
    lin_vel_y_range:
    - -0.5
    - 0.5
    ang_vel_range:
    - -1.0
    - 1.0
  note: walk with only front legs, body lean downward 45 degrees
pose:
  base_reset_pos:
  - 0.0
  - 0.0
  - 0.35
  base_reset_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  reset_joint_angles:
    FL_calf_joint: -1.5
    FL_hip_joint: 0.0
    FL_thigh_joint: 0.8
    FR_calf_joint: -1.5
    FR_hip_joint: 0.0
    FR_thigh_joint: 0.8
    RL_calf_joint: -1.5
    RL_hip_joint: 0.0
    RL_thigh_joint: 1.0
    RR_calf_joint: -1.5
    RR_hip_joint: 0.0
    RR_thigh_joint: 1.0
  base_init_pos:
  - 0.0
  - 0.0
  - 0.32287368178367615
  base_init_quat:
  - 0.9238795042037964
  - 0.0
  - 0.3826834559440613
  - 0.0
  body_init_pos:
  - 0.0
  - 0.0
  - 0.32287368178367615
  body_init_quat:
  - 0.9238795638084412
  - 0.0
  - 0.3826834559440613
  - 2.7533756608022486e-08
  default_joint_angles:
    FL_calf_joint: -2.143192768096924
    FL_hip_joint: -0.19423174858093262
    FL_thigh_joint: 1.008801817893982
    FR_calf_joint: -2.1460866928100586
    FR_hip_joint: 0.19474253058433533
    FR_thigh_joint: 1.0057873725891113
    RL_calf_joint: -1.9943864345550537
    RL_hip_joint: -0.209744393825531
    RL_thigh_joint: 0.43646326661109924
    RR_calf_joint: -1.987788200378418
    RR_hip_joint: 0.1996818482875824
    RR_thigh_joint: 0.43762779235839844
  gait:
    base_height_target: 0.30016183853149414
    duration:
    - 0.5
    - 0.5
    frequency:
    - 3.0
    - 3.0
    offset:
    - 0.0
    - 0.5
    stationary_position:
    - - -0.008444353938102722
      - 0.10091954469680786
    - - -0.0074319615960121155
      - -0.10092408210039139
