base_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
base_link_name: base
body_init_quat:
  - 1.0
  - 0.0
  - 0.0
  - 0.0
robot:
  asset_path: urdf/go2/urdf/go2.urdf
  merge_fixed_links: false
  name: anymal
  numeric_adjustment: true
  scale: 1.0
task: walk with four legs
