robot:
  name: shadow_hand
  asset_path: urdf/shadow_hand/shadow_hand_simplified.urdf
  scale: 2.0
  body_name: palm
  foot_names:
  - little_finger_distal
  - thumb_distal
  - index_finger_distal
  - middle_finger_distal
  links_to_keep:
  - little_finger_distal
  - thumb_distal
  - index_finger_distal
  - middle_finger_distal
  link_names:
  - palm
  - thumb_base
  - index_finger_knuckle
  - middle_finger_knuckle
  - ring_finger_knuckle
  - little_finger_metacarpal
  - thumb_proximal
  - index_finger_proximal
  - middle_finger_proximal
  - ring_finger_proximal
  - little_finger_knuckle
  - thumb_hub
  - index_finger_middle
  - middle_finger_middle
  - ring_finger_middle
  - little_finger_proximal
  - thumb_middle
  - index_finger_distal
  - middle_finger_distal
  - ring_finger_distal
  - little_finger_middle
  - thumb_distal
  - little_finger_distal
  dof_names:
  - thumb_joint1
  - index_finger_joint1
  - middle_finger_joint1
  - ring_finger_joint1
  - little_finger_joint1
  - thumb_joint2
  - index_finger_join2
  - middle_finger_joint2
  - ring_finger_joint2
  - little_finger_joint2
  - thumb_joint3
  - index_finger_joint3
  - middle_finger_joint3
  - ring_finger_joint3
  - little_finger_joint3
  - thumb_joint4
  - index_finger_joint4
  - middle_finger_joint4
  - ring_finger_joint4
  - little_finger_joint4
  - thumb_joint5
  - little_finger_joint5
  diameter: 0.26247963309288025
  mass: 0.07948381170051888
control:
  control_freq: 50
  kp: 40.0
  kd: 1.0
  armature: 0.05
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
    - -0.25
    - 0.5
    lin_vel_y_range:
    - -0.25
    - 0.25
    ang_vel_range:
    - -0.5
    - 0.5
  note: walk with palm parallel to the ground, middle finger pointing forward, all
    fingertips placing on the ground
pose:
  base_init_pos:
  - 0.0
  - 0.0
  - 0.08225830644369125
  base_init_quat:
  - 0.7071068286895752
  - 0.7071068286895752
  - 0.0
  - 0.0
  body_init_pos:
  - 0.0
  - 0.0
  - 0.08225830644369125
  body_init_quat:
  - 0.7071068286895752
  - 0.7071068286895752
  - 0.0
  - 0.0
  default_joint_angles:
    index_finger_join2: 0.864549994468689
    index_finger_joint1: 0.30755627155303955
    index_finger_joint3: 1.1047814041376114e-06
    index_finger_joint4: 0.2525692582130432
    little_finger_joint1: 0.05688490718603134
    little_finger_joint2: -0.14037741720676422
    little_finger_joint3: 0.38794878125190735
    little_finger_joint4: 0.876602053642273
    little_finger_joint5: 0.12953852117061615
    middle_finger_joint1: 0.3490658402442932
    middle_finger_joint2: 0.9616167545318604
    middle_finger_joint3: 1.5221230569295585e-05
    middle_finger_joint4: 0.02895417995750904
    ring_finger_joint1: 0.061825722455978394
    ring_finger_joint2: 0.7474096417427063
    ring_finger_joint3: 2.018680334003875e-06
    ring_finger_joint4: 1.5707905292510986
    thumb_joint1: 0.8559585213661194
    thumb_joint2: 0.6754357218742371
    thumb_joint3: 0.05021176487207413
    thumb_joint4: -0.6981316804885864
    thumb_joint5: 1.5707963705062866
  gait:
    base_height_target: 0.051446013152599335
    duration:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    frequency:
    - 3.0
    - 3.0
    - 3.0
    - 3.0
    offset:
    - 0.0
    - 0.5
    - 0.0
    - 0.5
    stationary_position:
    - - -0.03788549453020096
      - -0.13381043076515198
    - - 0.05609651654958725
      - -0.07477762550115585
    - - 0.019247330725193024
      - -0.13829706609249115
    - - -0.0026990463957190514
      - -0.1366378366947174
