robot:
  name: shadow_hand
  asset_path: urdf/shadow_hand/shadow_hand_simplified.urdf
  scale: 2.0
  body_name: palm
  foot_names:
  - index_finger_distal
  - middle_finger_distal
  - ring_finger_distal
  - thumb_distal
  - little_finger_distal
  links_to_keep:
  - index_finger_distal
  - middle_finger_distal
  - ring_finger_distal
  - thumb_distal
  - little_finger_distal
  link_names:
  - palm
  - thumb_base
  - index_finger_knuckle
  - middle_finger_knuckle
  - ring_finger_knuckle
  - little_finger_metacarpal
  - thumb_proximal
  - index_finger_proximal
  - middle_finger_proximal
  - ring_finger_proximal
  - little_finger_knuckle
  - thumb_hub
  - index_finger_middle
  - middle_finger_middle
  - ring_finger_middle
  - little_finger_proximal
  - thumb_middle
  - index_finger_distal
  - middle_finger_distal
  - ring_finger_distal
  - little_finger_middle
  - thumb_distal
  - little_finger_distal
  dof_names:
  - thumb_joint1
  - index_finger_joint1
  - middle_finger_joint1
  - ring_finger_joint1
  - little_finger_joint1
  - thumb_joint2
  - index_finger_join2
  - middle_finger_joint2
  - ring_finger_joint2
  - little_finger_joint2
  - thumb_joint3
  - index_finger_joint3
  - middle_finger_joint3
  - ring_finger_joint3
  - little_finger_joint3
  - thumb_joint4
  - index_finger_joint4
  - middle_finger_joint4
  - ring_finger_joint4
  - little_finger_joint4
  - thumb_joint5
  - little_finger_joint5
  diameter: 0.26247963309288025
  mass: 0.07948381170051888
control:
  control_freq: 50
  kp: 40.0
  kd: 1.0
  armature: 0.05
  damping: 0.0
learning:
  num_iterations: 3
  num_samples: 4
  num_logpoints: 10
  command:
    lin_vel_x_range:
    - -0.25
    - 0.5
    lin_vel_y_range:
    - -0.25
    - 0.25
    ang_vel_range:
    - -0.5
    - 0.5
  note: walk with palm parallel to the ground, middle finger pointing forward, all
    fingertips placing on the ground
pose:
  base_init_pos:
  - 0.0
  - 0.0
  - 0.08835683763027191
  base_init_quat:
  - 0.49999988079071045
  - 0.4999999403953552
  - 0.5000000596046448
  - 0.5000000596046448
  body_init_pos:
  - 0.0
  - 0.0
  - 0.08835683763027191
  body_init_quat:
  - 0.49999991059303284
  - 0.4999999701976776
  - 0.5000000596046448
  - 0.5000001192092896
  default_joint_angles:
    index_finger_join2: 0.3257831633090973
    index_finger_joint1: -0.15613922476768494
    index_finger_joint3: 0.3489384949207306
    index_finger_joint4: 1.5707963705062866
    little_finger_joint1: 0.12220004200935364
    little_finger_joint2: -0.269074022769928
    little_finger_joint3: 0.7976834774017334
    little_finger_joint4: 0.04536755383014679
    little_finger_joint5: 0.37140780687332153
    middle_finger_joint1: 0.2601180672645569
    middle_finger_joint2: 0.47193631529808044
    middle_finger_joint3: 0.7067288756370544
    middle_finger_joint4: 0.3093944489955902
    ring_finger_joint1: -0.20317380130290985
    ring_finger_joint2: 0.6390296816825867
    ring_finger_joint3: 0.4160537123680115
    ring_finger_joint4: 1.5707963705062866
    thumb_joint1: -0.7228057384490967
    thumb_joint2: 0.5423364043235779
    thumb_joint3: 0.19617286324501038
    thumb_joint4: 0.09906435012817383
    thumb_joint5: 0.0010344721376895905
  gait:
    base_height_target: 0.04463114216923714
    duration:
    - 0.6
    - 0.6
    - 0.6
    - 0.6
    - 0.6
    frequency:
    - 3.0
    - 3.0
    - 3.0
    - 3.0
    - 3.0
    offset:
    - 0.0
    - 0.0
    - 0.5
    - 0.5
    - 0.5
    stationary_position:
    - - 0.15639890730381012
      - 0.0426655039191246
    - - 0.14696526527404785
      - -0.0017658041324466467
    - - 0.14245270192623138
      - -0.02077598311007023
    - - 0.051142215728759766
      - 0.09118711203336716
    - - 0.12895016372203827
      - -0.04023844376206398
