robot:
  asset_path: urdf/shadow_hand/shadow_hand_simplified.urdf
  scale: 1.0
  merge_fixed_links: true
  numeric_adjustment: false
task: walk with palm parallel to the ground, middle finger pointing forward, all fingertips
  placing on the ground